version: '3'

services:

  api:
    build: './src/api'
    volumes:
      - './src/api:/backend'
    ports:
      - '8000:8000'

  www:
    build: './src/www'
    volumes:
      - './src/www:/frontend'
    ports:
      - '8080:8080'
